import CryptoJS from 'crypto-js';

const configuredSalt = process.env.NEXT_PUBLIC_ENCRYPTION_SALT;
if (!configuredSalt && process.env.NODE_ENV !== 'production') {
    console.warn('[Encryption] NEXT_PUBLIC_ENCRYPTION_SALT is not set. Using development fallback salt.');
}
const DEV_FALLBACK_SALT = 'dev-only-fallback-salt';

function getGlobalSalt(): string {
    if (configuredSalt) return configuredSalt;
    if (process.env.NODE_ENV === 'production') {
        throw new Error('NEXT_PUBLIC_ENCRYPTION_SALT is required in production');
    }
    return DEV_FALLBACK_SALT;
}

/**
 * Generates a deterministic shared key for a chat between two users.
 * Ensure the IDs are sorted so User A + User B generates the same key as User B + User A.
 */
export function generateChatKey(userId1: string, userId2: string): string {
    if (!userId1 || !userId2) throw new Error("Both user IDs are required to generate a chat key");
    
    // Sort the IDs alphabetically so the order doesn't matter
    const sortedIds = [userId1, userId2].sort().join(':');
    
    // Hash the combined string along with the secret global salt
    return CryptoJS.SHA256(`${sortedIds}-${getGlobalSalt()}`).toString(CryptoJS.enc.Hex);
}

/**
 * Encrypts a plaintext message using the shared chat key.
 * @param plaintext The message to encrypt
 * @param sharedKey The chat key generated by `generateChatKey`
 * @returns The encrypted ciphertext string
 */
export function encryptMessage(plaintext: string, sharedKey: string): string {
    if (!plaintext) return '';
    return CryptoJS.AES.encrypt(plaintext, sharedKey).toString();
}

/**
 * Decrypts a ciphertext string back into plaintext.
 * @param ciphertext The encrypted message
 * @param sharedKey The chat key generated by `generateChatKey`
 * @returns The decrypted plaintext, or a fallback error string if decryption fails
 */
export function decryptMessage(ciphertext: string, sharedKey: string): string {
    if (!ciphertext) return '';
    try {
        const bytes = CryptoJS.AES.decrypt(ciphertext, sharedKey);
        // If decryption produces empty/invalid UTF-8, fall back to raw text
        // (this handles old plain-text messages stored before encryption was added)
        const decryptedText = bytes.toString(CryptoJS.enc.Utf8);
        if (!decryptedText) return ciphertext; // Return original if decryption yields nothing
        return decryptedText;
    } catch {
        // Malformed UTF-8 or invalid ciphertext — treat as plain text
        return ciphertext;
    }
}
